language: php
dist: precise

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.2

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer global require "phpunit/phpunit=6.*"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script: phpunit
